export const marketplaceProducts = [
{
"id": 1,
"name": "Bosch Front Brake Pads (Set)",
"category": "Braking System",
"subcategory": "Brake Pads",
"brand": "Bosch",
"sku": "SP-BRK-BOS-001",
"price": 35000,
"stock": 45,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Lexus RX 350", "Honda Accord"],
"imageUrl": "https://m.media-amazon.com/images/I/61gEq1H34mL.jpg"
},
{
"id": 2,
"name": "Brembo High-Performance Rear Brake Pads",
"category": "Braking System",
"subcategory": "Brake Pads",
"brand": "Brembo",
"sku": "SP-BRK-BRE-002",
"price": 55000,
"stock": 18,
"compatibleVehicles": ["Mercedes-Benz C-Class (C300)", "BMW 3 Series (330i)", "BMW 5 Series (540i)"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi3TxLQr5LAYDDp06uXniLe6048-asG0ieZHVSgOuFPI3m-cyyudHCnvE&s=10"
},
{
"id": 3,
"name": "Toyota OEM Genuine Front Brake Rotors (Pair)",
"category": "Braking System",
"subcategory": "Brake Rotors",
"brand": "Toyota",
"sku": "SP-BRK-TOY-003",
"price": 95000,
"stock": 12,
"compatibleVehicles": ["Toyota Camry", "Toyota Highlander", "Toyota RAV4"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4eEiUtgTIj9xV06JCOKoO2pRpd14YI_MIjf5qdzyCtlvdQAiSxs8OO61-&s=10"
},
{
"id": 4,
"name": "PowerStop Ceramic Brake Pad & Rotor Kit",
"category": "Braking System",
"subcategory": "Brake Upgrade Kit",
"brand": "PowerStop",
"sku": "SP-BRK-POW-004",
"price": 185000,
"stock": 8,
"compatibleVehicles": ["Ford F-150", "Ford Mustang", "Toyota Land Cruiser"],
"imageUrl": "https://i5.walmartimages.com/seo/Power-Stop-Front-and-Rear-Ceramic-Brake-Pad-and-Drilled-and-Slotted-Rotor-Kit-K7566_d1fb38ad-123f-4f45-a8c0-5b30c88488b7.38697a0a9733b6afffd03b45b3dcbb05.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF"
},
{
"id": 5,
"name": "Ate Premium Brake Caliper assembly (Front-Left)",
"category": "Braking System",
"subcategory": "Brake Calipers",
"brand": "Ate",
"sku": "SP-BRK-ATE-005",
"price": 65000,
"stock": 6,
"compatibleVehicles": ["Volkswagen Golf", "Volkswagen Jetta", "Volkswagen Passat"],
"imageUrl": "https://i5.walmartimages.com/asr/5279390d-ad27-46b9-855e-0b40c1f3179f.d64821a2016142458d2af01384db5651.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF"
},
{
"id": 6,
"name": "NGK Iridium IX Spark Plug (Pack of 4)",
"category": "Electrical & Ignition",
"subcategory": "Spark Plugs",
"brand": "NGK",
"sku": "SP-IGN-NGK-006",
"price": 24000,
"stock": 150,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Civic", "Hyundai Elantra", "Kia Rio"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROnviDt93STyozRlsFT1qTW_hnHk0mHG-SB9fJpz3-aw&s"
},
{
"id": 7,
"name": "Denso Platinum Spark Plug (Pack of 6)",
"category": "Electrical & Ignition",
"subcategory": "Spark Plugs",
"brand": "Denso",
"sku": "SP-IGN-DEN-007",
"price": 42000,
"stock": 80,
"compatibleVehicles": ["Toyota Highlander", "Lexus RX 350", "Honda Pilot", "Nissan Pathfinder"],
"imageUrl": "https://m.media-amazon.com/images/I/71s7BXAIw2L._AC_UF894,1000_QL80_.jpg"
},
{
"id": 8,
"name": "Bosch Double Platinum Spark Plug (Pack of 4)",
"category": "Electrical & Ignition",
"subcategory": "Spark Plugs",
"brand": "Bosch",
"sku": "SP-IGN-BOS-008",
"price": 28000,
"stock": 110,
"compatibleVehicles": ["Mercedes-Benz C-Class (C300)", "BMW 3 Series (330i)", "Volkswagen Passat"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ67-JSX158UlNAb8AoPG0QlBps19WyZUSp_KBN0Gf6UQ&s"
},
{
"id": 9,
"name": "Denso Ignition Coil Assembly",
"category": "Electrical & Ignition",
"subcategory": "Ignition Coils",
"brand": "Denso",
"sku": "SP-IGN-DEN-009",
"price": 22000,
"stock": 64,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Toyota Highlander", "Toyota RAV4"],
"imageUrl": "https://m.media-amazon.com/images/I/715fBd6zmuL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 10,
"name": "Hanshin Ignition Coil Pack",
"category": "Electrical & Ignition",
"subcategory": "Ignition Coils",
"brand": "Hanshin",
"sku": "SP-IGN-HAN-010",
"price": 19500,
"stock": 42,
"compatibleVehicles": ["Honda Accord", "Honda Civic", "Honda CR-V"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZAN95_tgq3Ro8fbP9lxTqnfEs01Z9ro_vBkMhW77t5Oi_2My86DYwLlEL&s=10"
},
{
"id": 11,
"name": "Monroe OESpectrum Front Shock Absorber (Single)",
"category": "Suspension & Steering",
"subcategory": "Shock Absorbers",
"brand": "Monroe",
"sku": "SP-SUS-MON-011",
"price": 45000,
"stock": 30,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Accord", "Nissan Altima"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBcH5HeagQ2xVQAIpXxnJr18oh3WmhY6SPFtO8CTC_YA&s"
},
{
"id": 12,
"name": "KYB Excel-G Heavy Duty Rear Strut (Pair)",
"category": "Suspension & Steering",
"subcategory": "Struts",
"brand": "KYB",
"sku": "SP-SUS-KYB-012",
"price": 98000,
"stock": 14,
"compatibleVehicles": ["Toyota Highlander", "Lexus RX 350", "Honda Pilot", "Ford Explorer"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD3vZgPzhhWOhFdFCfsFk04fWD2HYPvYMuwCY-XTwdFl-zX8J0QJNHe1hj&s=10"
},
{
"id": 13,
"name": "Moog Front Lower Control Arm (Left-Side)",
"category": "Suspension & Steering",
"subcategory": "Control Arms",
"brand": "Moog",
"sku": "SP-SUS-MOO-013",
"price": 38000,
"stock": 25,
"compatibleVehicles": ["Toyota Corolla", "Honda Civic", "Hyundai Elantra", "Kia Cerato"],
"imageUrl": "https://www.suspension.com/productimages/moog/rk623872/jinx-moog-moog-rk623872-large-1.jpg"
},
{
"id": 14,
"name": "Moog Front Ball Joint (Heavy Duty)",
"category": "Suspension & Steering",
"subcategory": "Ball Joints",
"brand": "Moog",
"sku": "SP-SUS-MOO-014",
"price": 15000,
"stock": 75,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Ford Explorer", "Hyundai Sonata"],
"imageUrl": "https://m.media-amazon.com/images/I/61WPEGUasML._AC_UF894,1000_QL80_.jpg"
},
{
"id": 15,
"name": "Tie Rod End Link Outer Assembly",
"category": "Suspension & Steering",
"subcategory": "Tie Rod Ends",
"brand": "555 Three Five",
"sku": "SP-SUS-555-015",
"price": 12500,
"stock": 90,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Accord", "Nissan Sentra"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRBdwTTwBggP9rGB2ieUthOx9HMn1EBkYqccMpgPLRBYTaghu3XIfTr93V&s=10"
},
{
"id": 16,
"name": "Sway Bar Stabilizer Link (Front Pair)",
"category": "Suspension & Steering",
"subcategory": "Stabilizer Links",
"brand": "Sankei 555",
"sku": "SP-SUS-SAN-016",
"price": 18000,
"stock": 50,
"compatibleVehicles": ["Toyota RAV4", "Honda CR-V", "Hyundai Tucson", "Kia Sportage"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhLwqFr_SDaDFrOKFKJg6Fy6TA1OdS_UkRbz3yBGIpM8Ag0jxTVyJrbpqK&s=10"
},
{
"id": 17,
"name": "Mann-Filter Premium Air Filter",
"category": "Filters & Maintenance",
"subcategory": "Air Filters",
"brand": "Mann-Filter",
"sku": "SP-FLT-MAN-017",
"price": 9500,
"stock": 130,
"compatibleVehicles": ["Mercedes-Benz C-Class (C300)", "BMW 3 Series (330i)", "Volkswagen Golf"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNk0eDnVij0MZX_zm_ZL1v6jcxJeMaMVsZGolf2OLgRYvf1dxvYXjdxL4&s=10"
},
{
"id": 18,
"name": "Toyota Genuine Engine Air Filter",
"category": "Filters & Maintenance",
"subcategory": "Air Filters",
"brand": "Toyota",
"sku": "SP-FLT-TOY-018",
"price": 8000,
"stock": 200,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Toyota Highlander", "Toyota RAV4"],
"imageUrl": "https://m.media-amazon.com/images/I/81TALRE2qhL.jpg"
},
{
"id": 19,
"name": "Mobil 1 Extended Performance Spin-On Oil Filter",
"category": "Filters & Maintenance",
"subcategory": "Oil Filters",
"brand": "Mobil 1",
"sku": "SP-FLT-MOB-019",
"price": 7500,
"stock": 350,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Ford F-150", "Chevrolet Silverado"],
"imageUrl": "https://m.media-amazon.com/images/I/71AkOVf+QXL._AC_UF1000,1000_QL80_.jpg"
},
{
"id": 20,
"name": "Fram Ultra Synthetic Cabin Air Filter (Activated Carbon)",
"category": "Filters & Maintenance",
"subcategory": "Cabin Filters",
"brand": "Fram",
"sku": "SP-FLT-FRA-020",
"price": 11500,
"stock": 95,
"compatibleVehicles": ["Toyota Corolla", "Honda Civic", "Hyundai Elantra", "Nissan Altima"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhc6_XgRPL2OmJLzKooOQ-4WpYeiJP7klbQudKPCJFsQ&s"
},
{
"id": 21,
"name": "Mobil 1 Advanced Full Synthetic 5W-30 Engine Oil (5 Quarts)",
"category": "Filters & Maintenance",
"subcategory": "Engine Oil",
"brand": "Mobil 1",
"sku": "SP-FLUID-MOB-021",
"price": 38000,
"stock": 140,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://i5.walmartimages.com/seo/Mobil-1-Advanced-Full-Synthetic-Motor-Oil-5W-30-5-Quart_33e66b0d-65d5-45ba-98ca-e17393e9964e.0d95e132e4cdd054714b3482feb77f63.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF"
},
{
"id": 22,
"name": "Castrol EDGE Full Synthetic 5W-20 Motor Oil (1 Gallon)",
"category": "Filters & Maintenance",
"subcategory": "Engine Oil",
"brand": "Castrol",
"sku": "SP-FLUID-CAS-022",
"price": 34000,
"stock": 100,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://m.media-amazon.com/images/I/61FmZexyn2L._AC_UF894,1000_QL80_.jpg"
},
{
"id": 23,
"name": "Total Quartz 9000 Full Synthetic 5W-40 (5 Litres)",
"category": "Filters & Maintenance",
"subcategory": "Engine Oil",
"brand": "Total",
"sku": "SP-FLUID-TOT-023",
"price": 32000,
"stock": 160,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT0VugllryVLc--LOZVhnNiCb_toO9p-JH03oBlEUerhoCf2KFn79mGnFS&s=10"
},
{
"id": 24,
"name": "Abro Premium DOT 4 Brake Fluid (354ml)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Abro",
"sku": "SP-FLUID-ABR-024",
"price": 4500,
"stock": 220,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTvt4Xh62uNlLzuMTOyUfmVdm5E0EXE7HeP3SNRCxXBD3fH6NxIfdEAlY&s=10"
},
{
"id": 25,
"name": "Toyota Super Long Life Coolant Red (Pre-Mixed 50/50)",
"category": "Cooling System",
"subcategory": "Coolant",
"brand": "Toyota",
"sku": "SP-COOL-TOY-025",
"price": 18500,
"stock": 60,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Toyota Highlander", "Lexus RX 350"],
"imageUrl": "https://m.media-amazon.com/images/I/51Pj5poCgKL._AC_UF1000,1000_QL80_.jpg"
},
{
"id": 26,
"name": "Gates Premium Water Pump Assembly",
"category": "Cooling System",
"subcategory": "Water Pumps",
"brand": "Gates",
"sku": "SP-COOL-GAT-026",
"price": 32000,
"stock": 20,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Nissan Altima", "Ford Explorer"],
"imageUrl": "https://m.media-amazon.com/images/I/71GlO9fLDCL._AC_UF894,1000_QL80_.jpg"
},
{
"id": 27,
"name": "CSF Aluminum Engine Radiator",
"category": "Cooling System",
"subcategory": "Radiators",
"brand": "CSF",
"sku": "SP-COOL-CSF-027",
"price": 75000,
"stock": 15,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Lexus RX 350", "Hyundai Sonata"],
"imageUrl": "https://m.media-amazon.com/images/I/51pOLieBx9L._AC_UF894,1000_QL80_.jpg"
},
{
"id": 28,
"name": "Stant Engine Thermostat with Gasket (82°C)",
"category": "Cooling System",
"subcategory": "Thermostats",
"brand": "Stant",
"sku": "SP-COOL-STA-028",
"price": 9500,
"stock": 48,
"compatibleVehicles": ["Toyota Corolla", "Honda Civic", "Hyundai Elantra", "Kia Rio"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCKfP0kW1eD1AAigqZB6-MRDtEwQVB06e7La3J-whU5YKBKxp1zaBxWnOC&s=10"
},
{
"id": 29,
"name": "Panasonic 12V 75Ah Maintenance-Free Car Battery",
"category": "Electrical & Ignition",
"subcategory": "Batteries",
"brand": "Panasonic",
"sku": "SP-ELE-PAN-029",
"price": 85000,
"stock": 35,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCuWnI7-_UNRXVk8oZt8b9bTUXExGetnrY9ljgmYY23cfgPNtqa2lARDs&s=10"
},
{
"id": 30,
"name": "Optima YellowTop Dual-Purpose AGM Battery (750 CCA)",
"category": "Electrical & Ignition",
"subcategory": "Batteries",
"brand": "Optima",
"sku": "SP-ELE-OPT-030",
"price": 195000,
"stock": 10,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxTBcMKMH8f2zRys7gC7qhRDyVMRcx6jTa8xduKb8kRg&s"
},
{
"id": 31,
"name": "Bosch High-Output Alternator (150A)",
"category": "Electrical & Ignition",
"subcategory": "Alternators",
"brand": "Bosch",
"sku": "SP-ELE-BOS-031",
"price": 115000,
"stock": 12,
"compatibleVehicles": ["Mercedes-Benz C-Class (C300)", "BMW 3 Series (330i)", "BMW 5 Series (530i)"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi6g-D2tnyTppbhztK1o4JCr6Ge71s-IgPWyvC98L8SJAm72Tt2gxmatz3&s=10"
},
{
"id": 32,
"name": "Denso Remanufactured Starter Motor",
"category": "Electrical & Ignition",
"subcategory": "Starter Motors",
"brand": "Denso",
"sku": "SP-ELE-DEN-032",
"price": 68000,
"stock": 16,
"compatibleVehicles": ["Toyota Camry", "Toyota Highlander", "Lexus RX 350"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ_QVc6R0y7-gDFdWAy_qzLuB39Koxpxjj9fLyUJEOCA&s"
},
{
"id": 33,
"name": "Valeo Front Windshield Wiper Blade (Set of 2)",
"category": "Accessories & Comfort",
"subcategory": "Wiper Blades",
"brand": "Valeo",
"sku": "SP-ACC-VAL-033",
"price": 14000,
"stock": 110,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWx_enUcL7QPu3iEzcENZ6iOksxbz70NqVqwGxXhz_YA&s"
},
{
"id": 34,
"name": "Bosch Icon Beam Wiper Blade (Single, 22-Inch)",
"category": "Accessories & Comfort",
"subcategory": "Wiper Blades",
"brand": "Bosch",
"sku": "SP-ACC-BOS-034",
"price": 9500,
"stock": 85,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://m.media-amazon.com/images/I/71SWksINFkL.jpg"
},
{
"id": 35,
"name": "Continental Serpentine Multi-Rib Drive Belt",
"category": "Engine Parts",
"subcategory": "Belts",
"brand": "Continental",
"sku": "SP-ENG-CON-035",
"price": 14500,
"stock": 55,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Nissan Altima", "Hyundai Sonata"],
"imageUrl": "https://i.ebayimg.com/images/g/mJ8AAOSwQkloPbFO/s-l500.jpg"
},
{
"id": 36,
"name": "Gates Timing Belt Kit with Water Pump",
"category": "Engine Parts",
"subcategory": "Timing Kits",
"brand": "Gates",
"sku": "SP-ENG-GAT-036",
"price": 110000,
"stock": 9,
"compatibleVehicles": ["Toyota Camry 2018", "Honda Accord 2017", "Subaru Forester"],
"imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfQvWZd4OBQEDBlXGKhnTs35X1dyTSnhmWMveXaN3dccWm8w0LHkd9tNlJ&s=10"
},
{
"id": 37,
"name": "Exedy Premium Clutch Replacement Kit",
"category": "Transmission & Drivetrain",
"subcategory": "Clutch Kits",
"brand": "Exedy",
"sku": "SP-DRV-EXE-037",
"price": 135000,
"stock": 6,
"compatibleVehicles": ["Toyota Hilux", "Nissan Navara", "Peugeot Landtrek", "Ford Ranger"],
"imageUrl": "https://placehold.co/600x400/png?text=Exedy+Clutch+Kit"
},
{
"id": 38,
"name": "GKN Loebro CV Axle Shaft (Front-Right)",
"category": "Transmission & Drivetrain",
"subcategory": "CV Axles",
"brand": "GKN",
"sku": "SP-DRV-GKN-038",
"price": 72000,
"stock": 14,
"compatibleVehicles": ["Volkswagen Golf", "Volkswagen Passat", "BMW 3 Series (330i)"],
"imageUrl": "https://placehold.co/600x400/png?text=GKN+CV+Axle+Shaft"
},
{
"id": 39,
"name": "Timken Wheel Bearing and Hub Assembly",
"category": "Transmission & Drivetrain",
"subcategory": "Wheel Bearings",
"brand": "Timken",
"sku": "SP-DRV-TIM-039",
"price": 48000,
"stock": 32,
"compatibleVehicles": ["Toyota Highlander", "Lexus RX 350", "Ford Explorer", "Honda Pilot"],
"imageUrl": "https://placehold.co/600x400/png?text=Timken+Hub+Bearing"
},
{
"id": 40,
"name": "Lucas Oil heavy Duty Hub Oil & Gear Lubricant (80W-90, 1 Quart)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Lucas Oil",
"sku": "SP-FLUID-LUC-040",
"price": 9500,
"stock": 70,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Lucas+Gear+Oil"
},
{
"id": 41,
"name": "Philips X-tremeVision Pro150 H7 Headlight Bulbs (Pair)",
"category": "Electrical & Ignition",
"subcategory": "Lighting",
"brand": "Philips",
"sku": "SP-ELE-PHI-041",
"price": 19000,
"stock": 140,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Philips+H7+Headlight+Bulbs"
},
{
"id": 42,
"name": "Sylvania Zevo Red LED Tail Light Bulb (1157 Pack of 2)",
"category": "Electrical & Ignition",
"subcategory": "Lighting",
"brand": "Sylvania",
"sku": "SP-ELE-SYL-042",
"price": 12500,
"stock": 88,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Sylvania+LED+Tail+Light"
},
{
"id": 43,
"name": "Fel-Pro Engine Cylinder Head Gasket Set",
"category": "Engine Parts",
"subcategory": "Gaskets",
"brand": "Fel-Pro",
"sku": "SP-ENG-FEL-043",
"price": 54000,
"stock": 19,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Nissan Altima", "Hyundai Sonata"],
"imageUrl": "https://placehold.co/600x400/png?text=Fel-Pro+Head+Gasket"
},
{
"id": 44,
"name": "Victor Reinz Valve Cover Gasket Set",
"category": "Engine Parts",
"subcategory": "Gaskets",
"brand": "Victor Reinz",
"sku": "SP-ENG-VIC-044",
"price": 18000,
"stock": 35,
"compatibleVehicles": ["BMW 3 Series (330i)", "BMW 5 Series (530i)", "Mercedes-Benz C-Class (C300)"],
"imageUrl": "https://placehold.co/600x400/png?text=Victor+Reinz+Gasket"
},
{
"id": 45,
"name": "Walker Ultra Direct-Fit Catalytic Converter",
"category": "Engine Parts",
"subcategory": "Exhaust",
"brand": "Walker",
"sku": "SP-EXH-WAL-045",
"price": 165000,
"stock": 5,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Accord", "Honda Civic"],
"imageUrl": "https://placehold.co/600x400/png?text=Walker+Catalytic+Converter"
},
{
"id": 46,
"name": "Sensen Premium Front & Rear Strut Assembly Set (4 Pieces)",
"category": "Suspension & Steering",
"subcategory": "Suspension Kits",
"brand": "Sensen",
"sku": "SP-SUS-SEN-046",
"price": 195000,
"stock": 6,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Accord", "Nissan Altima"],
"imageUrl": "https://placehold.co/600x400/png?text=Sensen+Strut+Set"
},
{
"id": 47,
"name": "Denso A/C Compressor with Clutch",
"category": "Cooling System",
"subcategory": "Air Conditioning",
"brand": "Denso",
"sku": "SP-COOL-DEN-047",
"price": 145000,
"stock": 11,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Toyota Highlander", "Lexus RX 350"],
"imageUrl": "https://placehold.co/600x400/png?text=Denso+AC+Compressor"
},
{
"id": 48,
"name": "UAC Air Conditioning Condenser",
"category": "Cooling System",
"subcategory": "Air Conditioning",
"brand": "UAC",
"sku": "SP-COOL-UAC-048",
"price": 45000,
"stock": 25,
"compatibleVehicles": ["Toyota Corolla", "Honda Civic", "Hyundai Elantra", "Kia Cerato"],
"imageUrl": "https://placehold.co/600x400/png?text=UAC+AC+Condenser"
},
{
"id": 49,
"name": "Bosch Premium Fuel Filter Assembly",
"category": "Filters & Maintenance",
"subcategory": "Fuel Filters",
"brand": "Bosch",
"sku": "SP-FLT-BOS-049",
"price": 18500,
"stock": 40,
"compatibleVehicles": ["Mercedes-Benz C-Class (C300)", "BMW 3 Series (330i)", "Volkswagen Jetta"],
"imageUrl": "https://placehold.co/600x400/png?text=Bosch+Fuel+Filter"
},
{
"id": 50,
"name": "KYB Strut-Plus Fully Assembled Strut & Spring (Front Right)",
"category": "Suspension & Steering",
"subcategory": "Strut Assemblies",
"brand": "KYB",
"sku": "SP-SUS-KYB-050",
"price": 85000,
"stock": 12,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Lexus RX 350"],
"imageUrl": "https://placehold.co/600x400/png?text=KYB+Strut+Assembly"
},
{
"id": 51,
"name": "LAUNCH Creader 3001 Full OBD2 Diagnostic Scanner",
"category": "Tools & Diagnostics",
"subcategory": "Diagnostic Scanners",
"brand": "LAUNCH",
"sku": "TL-DIAG-LAU-051",
"price": 32000,
"stock": 35,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=LAUNCH+Creader+3001"
},
{
"id": 52,
"name": "Ancel AD310 OBDII Engine Fault Code Reader",
"category": "Tools & Diagnostics",
"subcategory": "Diagnostic Scanners",
"brand": "Ancel",
"sku": "TL-DIAG-ANC-052",
"price": 28000,
"stock": 50,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Ancel+Code+Reader"
},
{
"id": 53,
"name": "Autel MaxiCOM MK808 Professional Tablet Diagnostic Tool",
"category": "Tools & Diagnostics",
"subcategory": "Diagnostic Scanners",
"brand": "Autel",
"sku": "TL-DIAG-AUT-053",
"price": 345000,
"stock": 4,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Autel+MaxiCOM+MK808"
},
{
"id": 54,
"name": "Torin Big Red 3-Ton Hydraulic Trolley Floor Jack",
"category": "Tools & Diagnostics",
"subcategory": "Lifting Jacks",
"brand": "Torin",
"sku": "TL-LFT-TOR-054",
"price": 68000,
"stock": 22,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Torin+3-Ton+Floor+Jack"
},
{
"id": 55,
"name": "Torin Big Red 3-Ton Steel Jack Stands (Pair)",
"category": "Tools & Diagnostics",
"subcategory": "Lifting Jacks",
"brand": "Torin",
"sku": "TL-LFT-TOR-055",
"price": 34000,
"stock": 45,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Torin+Jack+Stands+Pair"
},
{
"id": 56,
"name": "WORKPRO 100-Piece Drive Socket Wrench Set",
"category": "Tools & Diagnostics",
"subcategory": "Hand Tools",
"brand": "WORKPRO",
"sku": "TL-HND-WOR-056",
"price": 45000,
"stock": 30,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=WORKPRO+Socket+Set"
},
{
"id": 57,
"name": "EPAuto 1/2-Inch Drive Click Torque Wrench (10-150 ft-lb)",
"category": "Tools & Diagnostics",
"subcategory": "Hand Tools",
"brand": "EPAuto",
"sku": "TL-HND-EPA-057",
"price": 28000,
"stock": 25,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=EPAuto+Torque+Wrench"
},
{
"id": 58,
"name": "Astro AI Digital Tire Pressure Gauge & Inflator Connection",
"category": "Tools & Diagnostics",
"subcategory": "Hand Tools",
"brand": "AstroAI",
"sku": "TL-HND-AST-058",
"price": 14500,
"stock": 65,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=AstroAI+Tire+Gauge"
},
{
"id": 59,
"name": "Craftsman 12-Piece Combination Wrench Set (Metric)",
"category": "Tools & Diagnostics",
"subcategory": "Hand Tools",
"brand": "Craftsman",
"sku": "TL-HND-CRA-059",
"price": 38000,
"stock": 40,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Craftsman+Wrench+Set"
},
{
"id": 60,
"name": "Cartman Heavy Duty Booster Jumper Cables (4 Gauge, 20 Feet)",
"category": "Tools & Diagnostics",
"subcategory": "Emergency Kits",
"brand": "Cartman",
"sku": "TL-EMG-CAR-060",
"price": 16500,
"stock": 120,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Cartman+Jumper+Cables"
},
{
"id": 61,
"name": "NOCO Boost Plus GB40 1000A UltraSafe Car Jump Starter",
"category": "Accessories & Comfort",
"subcategory": "Portable Power",
"brand": "NOCO",
"sku": "SP-ACC-NOC-061",
"price": 95000,
"stock": 28,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=NOCO+GB40+Jump+Starter"
},
{
"id": 62,
"name": "70mai Dash Cam Pro Plus+ A500S with GPS (Front & Rear Bundle)",
"category": "Accessories & Comfort",
"subcategory": "Car Electronics",
"brand": "70mai",
"sku": "SP-ACC-70M-062",
"price": 74000,
"stock": 35,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=70mai+A500S+Dash+Cam"
},
{
"id": 63,
"name": "Vantrue N4 3-Channel 4K Dash Cam (Front, Cabin and Rear)",
"category": "Accessories & Comfort",
"subcategory": "Car Electronics",
"brand": "Vantrue",
"sku": "SP-ACC-VAN-063",
"price": 185000,
"stock": 10,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Vantrue+N4+Dash+Cam"
},
{
"id": 64,
"name": "Yantek Dual USB Fast Car Charger (PD 3.0 & QC 3.0, Metal)",
"category": "Accessories & Comfort",
"subcategory": "Car Electronics",
"brand": "Yantek",
"sku": "SP-ACC-YAN-064",
"price": 6500,
"stock": 250,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Yantek+Car+Charger"
},
{
"id": 65,
"name": "Baseus Magnetic Car Phone Mount (Dashboard / Air Vent Mount)",
"category": "Accessories & Comfort",
"subcategory": "Mobile Accessories",
"brand": "Baseus",
"sku": "SP-ACC-BAS-065",
"price": 8500,
"stock": 190,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Baseus+Magnetic+Mount"
},
{
"id": 66,
"name": "iOttie Easy One Touch 5 Dashboard Car Mount",
"category": "Accessories & Comfort",
"subcategory": "Mobile Accessories",
"brand": "iOttie",
"sku": "SP-ACC-IOT-066",
"price": 18000,
"stock": 70,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=iOttie+Dashboard+Mount"
},
{
"id": 67,
"name": "FH Group Universal Fit Carpet Car Floor Mats (4-Piece Set)",
"category": "Accessories & Comfort",
"subcategory": "Interior Comfort",
"brand": "FH Group",
"sku": "SP-ACC-FHG-067",
"price": 16000,
"stock": 80,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=FH+Group+Floor+Mats"
},
{
"id": 68,
"name": "Motor Trend FlexTough All Weather Heavy Duty Rubber Floor Mats",
"category": "Accessories & Comfort",
"subcategory": "Interior Comfort",
"brand": "Motor Trend",
"sku": "SP-ACC-MOT-068",
"price": 28000,
"stock": 45,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Motor+Trend+Rubber+Mats"
},
{
"id": 69,
"name": "Custom Fit Breathable Outdoor Car Cover (Anti-UV Waterproof)",
"category": "Accessories & Comfort",
"subcategory": "Exterior Styling",
"brand": "Motor Trend",
"sku": "SP-ACC-MOT-069",
"price": 25000,
"stock": 60,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Accord", "Nissan Altima"],
"imageUrl": "https://placehold.co/600x400/png?text=Breathable+Car+Cover"
},
{
"id": 70,
"name": "Kayme Multi-Layer Waterproof Car Cover (Heavy Duty Reflective)",
"category": "Accessories & Comfort",
"subcategory": "Exterior Styling",
"brand": "Kayme",
"sku": "SP-ACC-KAY-070",
"price": 42000,
"stock": 35,
"compatibleVehicles": ["Toyota Highlander", "Lexus RX 350", "Ford Explorer", "Honda CR-V"],
"imageUrl": "https://placehold.co/600x400/png?text=Kayme+Waterproof+Cover"
},
{
"id": 71,
"name": "Windex Premium Windshield Washer Fluid Additive (Concentrate)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Windex",
"sku": "SP-FLUID-WIN-071",
"price": 3500,
"stock": 140,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Windex+Washer+Fluid"
},
{
"id": 72,
"name": "Denso Cabin Air Filter (Standard)",
"category": "Filters & Maintenance",
"subcategory": "Cabin Filters",
"brand": "Denso",
"sku": "SP-FLT-DEN-072",
"price": 6000,
"stock": 180,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Toyota Highlander", "Lexus RX 350"],
"imageUrl": "https://placehold.co/600x400/png?text=Denso+Cabin+Filter"
},
{
"id": 73,
"name": "Subaru OEM High-Performance ATF Fluid (1 Quart)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Subaru",
"sku": "SP-FLUID-SUB-073",
"price": 12000,
"stock": 48,
"compatibleVehicles": ["Subaru Forester", "Subaru Outback"],
"imageUrl": "https://placehold.co/600x400/png?text=Subaru+ATF+Fluid"
},
{
"id": 74,
"name": "Mercon LV Automatic Transmission Fluid (1 Quart)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Motorcraft",
"sku": "SP-FLUID-MOC-074",
"price": 8500,
"stock": 95,
"compatibleVehicles": ["Ford F-150", "Ford Explorer", "Ford Escape", "Ford Edge"],
"imageUrl": "https://placehold.co/600x400/png?text=Mercon+LV+ATF"
},
{
"id": 75,
"name": "Honda Genuine HG HCF-2 CVT Fluid (1 Quart)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Honda",
"sku": "SP-FLUID-HON-075",
"price": 14000,
"stock": 60,
"compatibleVehicles": ["Honda Accord", "Honda Civic", "Honda CR-V", "Honda HR-V"],
"imageUrl": "https://placehold.co/600x400/png?text=Honda+HCF-2+CVT+Fluid"
},
{
"id": 76,
"name": "Dayco Premium Timing Belt Gasket Kit",
"category": "Engine Parts",
"subcategory": "Gaskets",
"brand": "Dayco",
"sku": "SP-ENG-DAY-076",
"price": 45000,
"stock": 15,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Nissan Altima"],
"imageUrl": "https://placehold.co/600x400/png?text=Dayco+Timing+Belt+Gasket"
},
{
"id": 77,
"name": "STP Premium Oil Treatment (Oil Additive, 15 Fl. Oz)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "STP",
"sku": "SP-FLUID-STP-077",
"price": 5500,
"stock": 110,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=STP+Oil+Treatment"
},
{
"id": 78,
"name": "Sea Foam SF-16 Motor Treatment (Fuel System Additive)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Sea Foam",
"sku": "SP-FLUID-SEA-078",
"price": 8500,
"stock": 150,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Sea+Foam+Motor+Treatment"
},
{
"id": 79,
"name": "Techron Concentrate Plus Complete Fuel System Cleaner",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Chevron",
"sku": "SP-FLUID-CHV-079",
"price": 9000,
"stock": 120,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Chevron+Techron+Cleaner"
},
{
"id": 80,
"name": "Prestone Command Heavy Duty Antifreeze/Coolant Yellow",
"category": "Cooling System",
"subcategory": "Coolant",
"brand": "Prestone",
"sku": "SP-COOL-PRE-080",
"price": 14000,
"stock": 85,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Prestone+Yellow+Coolant"
},
{
"id": 81,
"name": "STP Heavy Duty Power Steering Fluid (12 Fl. Oz)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "STP",
"sku": "SP-FLUID-STP-081",
"price": 4000,
"stock": 130,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=STP+Power+Steering+Fluid"
},
{
"id": 82,
"name": "Ford OEM Motorcraft High-Output Alternator assembly",
"category": "Electrical & Ignition",
"subcategory": "Alternators",
"brand": "Motorcraft",
"sku": "SP-ELE-MOC-082",
"price": 165000,
"stock": 6,
"compatibleVehicles": ["Ford F-150", "Ford Explorer", "Ford Expedition"],
"imageUrl": "https://placehold.co/600x400/png?text=Motorcraft+Alternator"
},
{
"id": 83,
"name": "BMW OEM Genuine High-Output Ignition Coil Pack",
"category": "Electrical & Ignition",
"subcategory": "Ignition Coils",
"brand": "BMW",
"sku": "SP-IGN-BMW-083",
"price": 35000,
"stock": 24,
"compatibleVehicles": ["BMW 3 Series (330i)", "BMW 5 Series (540i)", "BMW X3", "BMW X5"],
"imageUrl": "https://placehold.co/600x400/png?text=BMW+Genuine+Ignition+Coil"
},
{
"id": 84,
"name": "WD-40 Multi-Use Smart Straw Lubricant Spray (12 Oz)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "WD-40",
"sku": "SP-FLUID-WD4-084",
"price": 4500,
"stock": 310,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=WD-40+Smart+Straw"
},
{
"id": 85,
"name": "Monroe Max-Lift Trunk Lift Support Struts (Pair)",
"category": "Suspension & Steering",
"subcategory": "Struts",
"brand": "Monroe",
"sku": "SP-SUS-MON-085",
"price": 18000,
"stock": 42,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Nissan Altima", "Hyundai Sonata"],
"imageUrl": "https://placehold.co/600x400/png?text=Monroe+Trunk+Supports"
},
{
"id": 86,
"name": "Moog Front Stabilizer Sway Bar Bushing Kit",
"category": "Suspension & Steering",
"subcategory": "Stabilizer Bushings",
"brand": "Moog",
"sku": "SP-SUS-MOO-086",
"price": 8500,
"stock": 68,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Accord", "Nissan Sentra"],
"imageUrl": "https://placehold.co/600x400/png?text=Moog+Stabilizer+Bushings"
},
{
"id": 87,
"name": "Wix Spin-On Lube Filter (Standard Heavy-Duty Oil Filter)",
"category": "Filters & Maintenance",
"subcategory": "Oil Filters",
"brand": "Wix Filters",
"sku": "SP-FLT-WIX-087",
"price": 5000,
"stock": 250,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Ford Explorer", "Hyundai Tucson"],
"imageUrl": "https://placehold.co/600x400/png?text=Wix+Oil+Filter"
},
{
"id": 88,
"name": "HKS Super Power Flow High-Performance Reloaded Intake Filter",
"category": "Engine Parts",
"subcategory": "Air Intake",
"brand": "HKS",
"sku": "SP-ENG-HKS-088",
"price": 58000,
"stock": 12,
"compatibleVehicles": ["Ford Mustang", "Toyota Camry", "Honda Civic"],
"imageUrl": "https://placehold.co/600x400/png?text=HKS+Super+Intake+Filter"
},
{
"id": 89,
"name": "K&N Premium High-Flow Lifetime Engine Air Filter",
"category": "Engine Parts",
"subcategory": "Air Intake",
"brand": "K&N",
"sku": "SP-ENG-KNN-089",
"price": 38000,
"stock": 35,
"compatibleVehicles": ["Toyota Camry", "Toyota Corolla", "Honda Accord", "Ford F-150"],
"imageUrl": "https://placehold.co/600x400/png?text=K%26N+Lifetime+Air+Filter"
},
{
"id": 90,
"name": "Ancel FX2000 All-System Professional Automotive Scan Tool",
"category": "Tools & Diagnostics",
"subcategory": "Diagnostic Scanners",
"brand": "Ancel",
"sku": "TL-DIAG-ANC-090",
"price": 145000,
"stock": 8,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Ancel+FX2000+Scanner"
},
{
"id": 91,
"name": "K&N Cold Air Intake Premium Upgrade Kit",
"category": "Engine Parts",
"subcategory": "Air Intake",
"brand": "K&N",
"sku": "SP-ENG-KNN-091",
"price": 285000,
"stock": 3,
"compatibleVehicles": ["Ford Mustang", "Ford F-150", "Toyota Land Cruiser"],
"imageUrl": "https://placehold.co/600x400/png?text=K%26N+Cold+Air+Intake"
},
{
"id": 92,
"name": "Gates Micro-V Stretch Fit Belt Installation Tool",
"category": "Tools & Diagnostics",
"subcategory": "Hand Tools",
"brand": "Gates",
"sku": "TL-HND-GAT-092",
"price": 18000,
"stock": 15,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Gates+Belt+Installation+Tool"
},
{
"id": 93,
"name": "Performance Tool Engine Oil Fluid Extraction Pump",
"category": "Tools & Diagnostics",
"subcategory": "Hand Tools",
"brand": "Performance Tool",
"sku": "TL-HND-PER-093",
"price": 25000,
"stock": 20,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Fluid+Extraction+Pump"
},
{
"id": 94,
"name": "Custom Leatherette Universal Car Seat Covers (Full Set)",
"category": "Accessories & Comfort",
"subcategory": "Interior Comfort",
"brand": "FH Group",
"sku": "SP-ACC-FHG-094",
"price": 68000,
"stock": 30,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Leatherette+Seat+Covers"
},
{
"id": 95,
"name": "Brembo High Performance Brake Fluid (DOT 4 Premium, 1L)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Brembo",
"sku": "SP-FLUID-BRE-095",
"price": 11000,
"stock": 140,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Brembo+DOT+4+Fluid"
},
{
"id": 96,
"name": "Abro Engine Degreaser and Cleaner Spray (450ml)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Abro",
"sku": "SP-FLUID-ABR-096",
"price": 4500,
"stock": 190,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Abro+Engine+Degreaser"
},
{
"id": 97,
"name": "Gunk Liquid Wrench Penetrating Oil Multi-Lube Spray",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "Gunk",
"sku": "SP-FLUID-GUN-097",
"price": 5000,
"stock": 160,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=Liquid+Wrench+Spray"
},
{
"id": 98,
"name": "Custom Fit Thick Rubber Cargo Trunk Liner Mat",
"category": "Accessories & Comfort",
"subcategory": "Interior Comfort",
"brand": "Motor Trend",
"sku": "SP-ACC-MOT-098",
"price": 19500,
"stock": 55,
"compatibleVehicles": ["Toyota Camry", "Honda Accord", "Toyota Highlander", "Lexus RX 350"],
"imageUrl": "https://placehold.co/600x400/png?text=Trunk+Cargo+Liner"
},
{
"id": 99,
"name": "EPAuto Universal High contrast Digital Tire Inflator with Air Hose",
"category": "Tools & Diagnostics",
"subcategory": "Emergency Kits",
"brand": "EPAuto",
"sku": "TL-EMG-EPA-099",
"price": 28000,
"stock": 70,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=EPAuto+Tire+Inflator"
},
{
"id": 100,
"name": "STP Complete Fuel System Treatment Cleaner (12 Fl Oz)",
"category": "Filters & Maintenance",
"subcategory": "Fluids",
"brand": "STP",
"sku": "SP-FLUID-STP-100",
"price": 7500,
"stock": 130,
"compatibleVehicles": ["Universal"],
"imageUrl": "https://placehold.co/600x400/png?text=STP+Fuel+System+Treatment"
}
];
